server:
  port: 8001

spring:
  application:
    name: batch
  datasource:
#    druid:
    url: jdbc:mysql://localhost:3306/bjpowernode?serverTimeZone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 1234


  batch:
    initialize-schema: always
    schema: classpath:/org/springframework/batch/core/schema-mysql.sql
#    job:
#      names: parentJob

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.baidu.batch.entities